### ISSUE TITLE
Child Domain Filter Returns Null

### ISSUE THREAD

**Issue by PeterSchwarzHPI** [divad1196/odoo_graphql#23] opened 2023-06-12 08:22 UTC
**Describe the bug**
If I query on a project's tasks (could probably be every other data model) through projects with a domain on the tasks, in some cases I receive an array filled with null values rather than an empty array.

**To Reproduce**
Query in a way as shown in the screenshots.
The main difference between those screenshots seems that the tasks in one project are not empty (or there is a second project being queried).

**Expected behavior**
If the query filters by domain an empty array should be returned in the case no child records can be fetched.

**Screenshots**
Correct behaviour:
![](https://user-images.githubusercontent.com/1878447/242898728-5a6d43e8-9b33-4aba-9cef-eb29f3122c2a.png)

Wrong behaviour:
![](https://user-images.githubusercontent.com/1878447/242899513-184c2aa5-6bf0-40b7-8ce9-967b6ef68237.png)

**Comment by divad1196** [comment] 2023-06-12 10:35
@PeterSchwarzHPI Should be fixed in PR #24 
Can you confirm?

This was caused by shortcut when many2many/one2many only have one record. I added a unitary test for this scenario.

**Comment by divad1196** [comment] 2023-10-31 21:14
Hi @PeterSchwarzHPI  I am closing the issue since I never got a response.
I hope it fixed your issue.

As always, thank you for the reporting.

**Closed as completed by divad1196** 2023-10-31 21:14 UTC
