### ISSUE TITLE
[Bug]: Doesn't work on 17

### ISSUE THREAD

**Issue by tchenevi** [divad1196/odoo_graphql#34] opened 2024-04-04 13:23 UTC
### What happened?

on request on mydomain.com/graphql i get this message :

The following modules failed to load because of an error, you may find more information in the devtools console:
@web/core/browser/browser
The following modules are needed by other modules but have not been defined, they may not be present in the correct asset bundle:
@web/core/l10n/translation
@web/core/utils/render
@web/core/utils/functions
@web/core/utils/concurrency
@web/core/utils/numbers
@web/core/registry
@web/core/l10n/localization
@web/core/utils/hooks
@web/core/utils/timing
@web/core/hotkeys/hotkey_service
@web/core/position_hook
The following modules could not be loaded because they have unmet dependencies, this is a secondary error which is likely caused by one of the above problems:
@web/legacy/js/core/dialog
@web/legacy/js/core/dom
@web/legacy/js/core/mixins
@web/legacy/js/core/service_mixins
@web/legacy/js/core/widget
@web/env
@web/core/action_swiper/action_swiper
@web/core/assets
@web/core/autocomplete/autocomplete

![Capture d’écran 2024-04-04 à 15 23 19](https://github.com/divad1196/odoo_graphql/assets/42489698/3bdd5b2b-4133-42c7-9816-cdd16fdc55b5)

### What did you expect?

Expecting to see graphql response

### Odoo Version

17

**Comment by divad1196** [comment] 2024-04-05 04:58
Hi,

Since graphql is an API, it is strange that you have a browser error message. Also, this error message is famous on wrong Odoo install which lead the generated assets to be broken.

Can you explain how you did the request? Like a screenshot where we see  the payload and how you will send it?

**Comment by tchenevi** [comment] 2024-04-05 07:50
Hi,
Thanks  for your response. I ran the request on insomnia and the screenshot is the preview of the response
![Capture d’écran 2024-04-05 à 09 50 12](https://github.com/divad1196/odoo_graphql/assets/42489698/02a1f38e-9252-4e92-8e30-1c54569269d0)

**Comment by divad1196** [comment] 2024-04-06 14:02
@tchenevi Hi again, I checked it again and it is working perfectly fine.
I even installed and used insomnia just to reproduce your situation in case it was linked to the tool used.
![image](https://github.com/divad1196/odoo_graphql/assets/43037556/49429906-60d7-48df-b1a4-a9f8a78ec9e3)


As I said, what you get is an error coming from a wrong Odoo install, or maybe an upgrade is messed up. At least, your assets are wrongly generated (btw, this module does not impact the general assets), you will need to investigate your installation on your side. Furthermore, this is a rendered issue from a text/html content-type, so you also might have asked the wrong url which should be `/graphql`; This module only responds with json responses even when it completely crashes and nothing works.

I am hence closing this issue since this has nothing to do with the module.
Have a nice day and good luck resolving your issue.

---

Some notes when using Insomnia for when your issue is fixed:
* Insomnia will try to add the `Content-type: application/json` header for graphql by default. You **should** remove that (this is part of the module documentation, and this comes from a limitation on Odoo's controller. This limitation seems that have been removed in V17, but I don't guarantee anything when using this header)
    
    ![image](https://github.com/divad1196/odoo_graphql/assets/43037556/66b283f3-1284-41c3-8eb0-ab070f5f47c7)

   I am seeing that you have at 3 headers defined when 0 are expected (maybe 1 if manually manage the Authorization header)
* Don't forget to define the `Authorization` header to access private resources
   
   ![image](https://github.com/divad1196/odoo_graphql/assets/43037556/62c9ec72-1336-4788-ba3b-3c08d36718f3)

**Closed as completed by divad1196** 2024-04-06 14:02 UTC
Labels: bug
